#!/usr/bin/env python
from setup_utils import *
import os

# ids.storage_file

actions, options, arg = getActions()
props = actions.getGlassfish("ids.storage_file-setup.properties", ["glassfish", "port"])

prop_lists = {}
prop_lists["ids.storage_file.main.properties"] = ["zipDir", "dir", "preparedDir"]
prop_lists["ids.storage_file.archive.properties"] = ["zipDir"]


if arg == "CONFIGURE":
    for prop_name, prop_list in prop_lists.items():
        actions.configure(prop_name, prop_list)
    actions.setConfigured()

elif arg == "INSTALL":
    
    actions.checkConfigured()
    
    for prop_name, prop_list in prop_lists.items():
        actions.getProperties(prop_name, prop_list)
        actions.installFile(prop_name)
   
    try:          
        actions.installToApplibs("ids.storage_file*.jar")
    except Exception, e:
        raise
        abort(str(e))
                
else:  # UNINSTALL
    
    for prop_name in prop_lists:
        actions.removeFile(prop_name)
    
    try:
        actions.removeFromApplibs("ids.storage_file*.jar")        
    except Exception, e:
        abort(str(e))       
    
            
    
